### ISSUE TITLE
Default shortcut

### ISSUE THREAD

**Issue by vors** [megaserg/gototab-chrome-extension#13]
Current is `Ctrl+Shift+E`. It uses 3 fingers on the left hand.
I would prefer to move letter to the right hand (like `P`).
The only concern about `P`: it's already used for system printing.

**Comment by megaserg** [comment]
Yeah I tried Ctrl+Shift+P as a default initially and couldn't understand why it's not working. I assumed Chrome is preventing extensions from having shortcuts conflicting with existing ones.

**Comment by vors** [comment]
I see. But it can be changed later from extensions tab. How about `Ctrl+Shift+L` ?

**Comment by megaserg** [comment]
On my Mac, Ctrl+Shift+L launches Safari when text is selected. And Ctrl+L is "select all in address bar".

**Comment by vors** [comment]
`Ctrl+Shift+K`?

**Comment by megaserg** [comment]
Changed to Ctrl+Shift+K

**Comment by vors** [comment]
:+1:
