### ISSUE TITLE
Support Up/Down keys to move the selection

### ISSUE THREAD

**Issue by vors** [megaserg/gototab-chrome-extension#4]

**Comment by megaserg** [comment]
Done.

**Comment by vors** [comment]
@megaserg maybe consider perform pull requests from feature branches instead of direct push. This way people who are watching (currently it's me) would have an option to comment directly on PR and provide feedback. If you are feel it's too complicated process for such earlier state of developing, it's also fine.

**Comment by megaserg** [comment]
Let's try, should be interesting!
