### ISSUE TITLE
Support fuzzy matching

### ISSUE THREAD

**Issue by aslushnikov** [megaserg/gototab-chrome-extension#9]
I've seen a TODO regarding fuzzy matching of strings.

We have the same Ctrl-O dialog in DevTools, and as a part of the effort we've implemented and heavily optimized the fuzzy matching algorithm. Might be useful: [fuzzy matching implementation](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/devtools/front_end/sources/FilePathScoreFunction.js&q=FilePathScor&sq=package:chromium&l=1)

**Comment by vors** [comment]
cool, will check it out. There is #2 for this
